dvpOAuth/__init__.py,sha256=Z_SG00-_IdL-KWwV7wGg3FpIDWrUAlBUa5jUbn36NFM,163
dvpOAuth/class_OAuth.py,sha256=Uy0u09qus1njo55GM4yMpD8s6Kzpj53BZwvX4ybro6U,16708
dvpOAuth/error.py,sha256=Y3BjsevsSGMDVVdn6ztiQMcGNtB6lySkNPoL7y4BT-Q,131
dvpOAuth/util.py,sha256=A7ZoIm1mjYwD4X9aommSZRYpi9ZidUuqMd2OYf1Ee64,743
dvpOAuth-0.0.19.dist-info/LICENSE,sha256=47DEQpj8HBSa-_TImW-5JCeuQeRkm5NMpJWZG3hSuFU,0
dvpOAuth-0.0.19.dist-info/METADATA,sha256=FvRKbhUsuWMJZgHYXHuMCo0IwAUH10KGoVZ4I-qc7v8,992
dvpOAuth-0.0.19.dist-info/WHEEL,sha256=2wepM1nk4DS4eFpYrW1TTqPcoGNfHhhO_i5m4cOimbo,92
dvpOAuth-0.0.19.dist-info/top_level.txt,sha256=14UgmlstFHh0UvlWIljRlFO26u2OesXzFC8SsWFZRmw,9
dvpOAuth-0.0.19.dist-info/RECORD,,
